version: '3'
services:
  #　先程作成したイメージを指定
  app:
    # Dockerfileを指定することも可能
    # https://qiita.com/kai_kou/items/eaafa3cb15e1496f50ec
    image: ubuntu-nginx
    ports:
      - 8080:80

  # 利用するイメージを追加
  mysql:
    image: mysql:8.0-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8081:80

